# permissions for end users to view mysqlservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysqluser-viewer-role
rules:
- apiGroups:
  - azure.microsoft.com
  resources:
  - mysqlusers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - azure.microsoft.com
  resources:
  - mysqlusers/status
  verbs:
  - get
