apiVersion: v1
entries:
  azure-service-operator:
  - apiVersion: v1
    appVersion: 0.1.0
    created: "2020-01-16T20:59:35.15759-08:00"
    description: Deploy components and dependencies of azure-service-operator
    digest: de800180f9ec210e90308a2f559784685656b14bd8ab12ea265e132deff2c107
    home: https://github.com/Azure/azure-service-operator
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator
    urls:
    - azure-service-operator-0.1.0.tgz
    version: 0.1.0
generated: "2020-01-16T20:59:35.154162-08:00"
