apiVersion: v1
entries:
  azure-service-operator:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2020-07-02T10:30:55.191248-06:00"
    dependencies:
    - condition: azureUseMI
      name: aad-pod-identity
      repository: https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts
      version: 1.5.5
    description: Deploy components and dependencies of azure-service-operator
    digest: b2343088d70b70ba2fdfc80b7b0faf722e13078681b5d9683119c102b18d065d
    home: https://github.com/Azure/azure-service-operator
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator
    urls:
    - azure-service-operator-0.1.0.tgz
    version: 0.1.0
generated: "2020-07-02T10:30:55.186109-06:00"
