apiVersion: v1
entries:
  azure-service-operator:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2020-06-24T17:25:15.791195-06:00"
    dependencies:
    - condition: azureUseMI
      name: aad-pod-identity
      repository: https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts
      version: 1.5.5
    description: Deploy components and dependencies of azure-service-operator
    digest: a06fcc4b2eb934029da1dd617039435c66998e8482469bb245e37fff41398563
    home: https://github.com/Azure/azure-service-operator
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator
    urls:
    - azure-service-operator-0.1.0.tgz
    version: 0.1.0
generated: "2020-06-24T17:25:15.787739-06:00"
