apiVersion: azure.microsoft.com/v1alpha1
kind: Storage
metadata:
  name: storagesamplegfdsa
spec:
  location: westus
  resourceGroup: resourcegroup-azure-operators
  sku:
    name: Standard_RAGRS
  kind: StorageV2
  properties:
    accessTier: Hot
    supportsHttpsTrafficOnly: true
# Optional: networkRule
    networkRule:
     bypass: AzureServices # Possible values are AzureServices, Metrics, None, Logging
     defaultAction: Allow # Possible values are Allow, Deny
     virtualNetworkRules: 
       - subnetId: /subscriptions/08daa385-27fa-477a-b556-a9ead8b270d9/resourceGroups/resourcegroup-azure-operator/providers/Microsoft.Network/virtualNetworks/virtualnetwork-sample/subnets/test1
     ipRules:
       - ipAddressOrRange: 2.2.0.0/24
       - ipAddressOrRange: 2.2.2.1
        

