apiVersion: azure.microsoft.com/v1alpha1
kind: CosmosDB
metadata:
  name: cosmosdb-sample1908xyzkj
spec:
  kind: GlobalDocumentDB
  location: westus
  resourceGroup: resourcegroup-azure-operators
  properties:
    databaseAccountOfferType: Standard
#optional for network rule set
#    isVirtualNetworkFilterEnabled: true
#  virtualNetworkRules:
#    - subnetId: /subscriptions/{subscription_id}/resourceGroups/{resourcegroup}/providers/Microsoft.Network/virtualNetworks/{vnet_name}/subnets/{subnet_name}
#      ignoreMissingServiceEndpoint: false


