azureTenantID: ""
azureSubscriptionID: ""

# Authentication - Service Principal
azureClientID: ""
azureClientSecret: ""

# Authentication - Managed Identity
azureUseMI: ""

# Optional, if using KeyVault to store secrets
azureOperatorKeyvault: ""

image:
  repository: mcr.microsoft.com/k8s/azure-service-operator:0.0.9150