apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: azureoperator-serving-cert
  namespace: {{ .Values.namespace }}
spec:
  dnsNames:
  - azureoperator-webhook-service.azureoperator-system.svc
  - azureoperator-webhook-service.azureoperator-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: azureoperator-selfsigned-issuer
  secretName: webhook-server-cert
